export const onboardingCopy = {
  ru: {
    intro: 'Ваш путь начинается здесь',
    steps: [
      'Какой язык хотите изучать?',
      'Как хорошо вы знаете язык?',
      'Для чего вы учитесь?',
      'Выберите первый шаг',
    ],
    hints: [
      'Выберите язык с доступными курсами. Позже можно выбрать другой.',
      'Это поможет подобрать начало. Здесь нет неправильного ответа.',
      'Небольшая цель поможет заниматься регулярно.',
      'Начните с основ или пройдите тест, чтобы найти свой уровень.',
    ],
    experience: [
      'Начинаю с нуля',
      'Знаю немного',
      'Уже могу общаться',
      'Не уверен',
    ],
    purposes: ['Для путешествий', 'Для работы', 'Для учёбы', 'Для себя'],
    daily: 'Сколько времени в день?',
    minutes: 'минут',
    back: 'Назад',
    next: 'Продолжить',
    basics: 'Начать с основ',
    test: 'Определить уровень',
    skip: 'Пропустить тест и начать с A1',
    testHint:
      'Ответьте на вопросы, чтобы подобрать начало обучения. Тест также останется в разделе «Тесты уровня».',
    basicsHint:
      'Первые слова, знакомство и простые фразы. Начните с первого урока A1.',
    unavailable:
      'Начало с A1 без теста пока недоступно. Ваш выбор сохранён. Сейчас можно определить уровень или вернуться к этому шагу позже.',
    error: 'Не удалось загрузить данные. Попробуйте ещё раз.',
    empty: 'Пока нет языков с доступными курсами.',
    retry: 'Повторить',
    step: 'Шаг',
    summary: 'Ваш план',
    storage: 'План сохраняется в этом браузере.',
    preferences: 'Язык и оформление',
    loading: 'Загружаем доступные языки…',
  },
  en: {
    intro: 'Your journey starts here',
    steps: [
      'Which language would you like to learn?',
      'How well do you know it?',
      'What are you learning for?',
      'Choose your first step',
    ],
    hints: [
      'Choose a language with available courses. You can change it later.',
      'This helps you choose a starting point. There is no wrong answer.',
      'A small daily goal helps you build a habit.',
      'Start with the basics or take a test to find your level.',
    ],
    experience: [
      'Starting from scratch',
      'I know a little',
      'I can have conversations',
      'Not sure',
    ],
    purposes: ['Travel', 'Work', 'Study', 'For myself'],
    daily: 'How much time each day?',
    minutes: 'minutes',
    back: 'Back',
    next: 'Continue',
    basics: 'Start with the basics',
    test: 'Find my level',
    skip: 'Skip the test and start A1',
    testHint:
      'Answer questions to find your starting point. You can also find the test under Level tests.',
    basicsHint:
      'First words, introductions and simple phrases. Begin with your first A1 lesson.',
    unavailable:
      'Starting A1 without a test is not available yet. Your choices are saved. Take the placement test now or return to this step later.',
    error: 'Could not load the data. Please try again.',
    empty: 'No languages with available courses yet.',
    retry: 'Retry',
    step: 'Step',
    summary: 'Your plan',
    storage: 'Your plan is saved in this browser.',
    preferences: 'Language and appearance',
    loading: 'Loading available languages…',
  },
  ky: {
    intro: 'Сиздин жолуңуз ушул жерден башталат',
    steps: [
      'Кайсы тилди үйрөнгүңүз келет?',
      'Тилди канчалык билесиз?',
      'Эмне үчүн үйрөнөсүз?',
      'Биринчи кадамды тандаңыз',
    ],
    hints: [
      'Курстары бар тилди тандаңыз. Кийин башка тилди тандасаңыз болот.',
      'Бул баштоо үчүн ылайыктуу деңгээлди тандоого жардам берет.',
      'Күн сайын чакан максат менен машыгыңыз.',
      'Негиздерден баштаңыз же деңгээлиңизди тест менен аныктаңыз.',
    ],
    experience: [
      'Нөлдөн баштайм',
      'Бир аз билем',
      'Баарлаша алам',
      'Так билбейм',
    ],
    purposes: ['Саякат үчүн', 'Жумуш үчүн', 'Окуу үчүн', 'Өзүм үчүн'],
    daily: 'Күнүнө канча убакыт?',
    minutes: 'мүнөт',
    back: 'Артка',
    next: 'Улантуу',
    basics: 'Негиздерден баштоо',
    test: 'Деңгээлди аныктоо',
    skip: 'Тестти өткөрүп, A1ден баштоо',
    testHint:
      'Окууну кайдан баштоону аныктоо үчүн суроолорго жооп бериңиз. Тест «Деңгээл тесттери» бөлүмүндө да болот.',
    basicsHint:
      'Алгачкы сөздөр, таанышуу жана жөнөкөй сүйлөмдөр. Биринчи A1 сабагынан баштаңыз.',
    unavailable:
      'A1ди тестсиз баштоо азырынча жеткиликсиз. Тандооңуз сакталды. Азыр тесттен өтүңүз же бул кадамга кийин кайтыңыз.',
    error: 'Маалымат жүктөлгөн жок. Кайра аракет кылыңыз.',
    empty: 'Курстары бар тилдер азырынча жок.',
    retry: 'Кайталоо',
    step: 'Кадам',
    summary: 'Сиздин планыңыз',
    storage: 'План ушул браузерде сакталат.',
    preferences: 'Тил жана көрүнүш',
    loading: 'Тилдер жүктөлүүдө…',
  },
};
